config/routes.rb
CatRental::Application.routes.draw do
  # Great: post 'cats' => 'cats#create', as: 'create_cat'

  resources :cats
  resources :cat_rental_requests
  resources :users, :only => [:show, :create, :new, :index]
  resources :sessions, :only => [:new, :create]

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :presence => :true

  has_many :cat_rental_requests, :dependent => :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :begin_date, :end_date, :status
  validate :overlap?

  validates :begin_date, :end_date, :presence => :true

  belongs_to :cat

  before_save :default_values
  def default_values
    self.status ||= 'undecided'
  end

  def overlap?
    possible_conflicts = CatRentalRequest.where(
      "cat_rental_requests.id != ? AND cat_rental_requests.cat_id = ?",
      self.id,
      self.cat_id
    )

    conflict = possible_conflicts.any? do |cat|
      self.begin_date.between?(cat.begin_date, cat.end_date) &&
      self.end_date.between?(cat.begin_date, cat.end_date)
    end
    if conflict
      self.errors[:base] << "Dates overlap"
    end
  end

  def approve
    self.status = 'approved'
    self.save
  end

  def deny
    self.status = 'denied'
    self.save
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password

  validates :username, :uniqueness => { :scope => :password }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user = User.find_by_token(session[:token])
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(params[:cat_rental_request])
    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render :new
    end
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end

  def update
    @request = CatRentalRequest.find(params[:id])
    if params[:cat_rental_request][:status] ==  "deny"
      @request.deny
    else
      @request.approve
    end
    redirect_to cat_url(@request.cat.id)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_filter :current_user

  def index
    @all_cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new()
    render :new
  end

  def create
    @cat = Cat.new(params[:cat])
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    if @current_user.id == @cat.user_id
      render :edit
    else
      render :text => "Can't edit someone else's cat!"
    end
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(params[:cat])
    redirect_to cat_url(@cat)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_username_and_password(
      params[:user][:username],
      params[:user][:password]
      )

    if @user
      @token = SecureRandom::urlsafe_base64(16)
      @user.update_attribute(:token, @token)

      session[:token] = @token
      redirect_to user_url(@user.id)
    else
      render :back
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @token = session[:token]
    @user = User.find_by_token(session[:token])

    if @token && @user
      render :text => "Welcome #{@user.username}!"
    else
      redirect_to new_session_url
    end
  end

  def new
    render :new
  end

  def show
    @token = session[:token]
    @me = User.find_by_token(@token)

    if @token
      @user_page = User.find_by_id(params[:id])
      if not @user_page
        render :text => "No such user!"
      elsif @me != @user_page
        render :text => "This is #{@user_page.username}'s page!"
      else
        redirect_to users_url
      end
    else
      redirect_to new_session_url
    end
  end

  def create
    @user = User.new(params[:user])
    @token = SecureRandom::urlsafe_base64(16)
    @user.token = @token

    if @user.save
      session[:token] = @token
      redirect_to user_url(@user.id)
    else
      render :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<%= form_for @cat_rental_request, url: cat_rental_requests_path do |f| %>


<%= f.label :cat_id %>
<%= f.select :cat_id, options_for_select(
  Cat.all.map { |cat| ["#{cat.name}, born: #{cat.birth_date} (id: #{cat.id})", cat.id]}, :cat_id
) %>



<label for="begin_date">Begin Date</label>
<input type="date" name="cat_rental_request[begin_date]" id="begin_date">

<label for="end_date">End Date</label>
<input type="date" name="cat_rental_request[end_date]" id="end_date">


<%= f.submit "Continue" %>
<% end %>

app/views/cat_rental_requests/show.html.erb
<h1>Your Rental for <%= @cat_rental_request.cat.name %></h1>

<ul>
  <li>Begin Date: <%= @cat_rental_request.begin_date %></li>
  <li>End Date: <%= @cat_rental_request.end_date%></li>
</ul>

app/views/cats/edit.html.erb
<form action="<%=cat_path%>" method="post">
<input type="hidden" name="_method" value="put">

<label>Name<input type="text" name="cat[name]" value="<%=@cat.name %>"></label>

<label>Age<input type="text" name="cat[age]" value="<%=@cat.age %>"></label>

<label>Sex<input type="text" name="cat[sex]" value="<%=@cat.sex %>"></label>

<input type="hidden" name="cat[user_id]" value="<%=
  User.find_by_token(session[:token]).id
%>">

<label>Birth Date
<input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%=@cat.birth_date %>"></label>

<label>Color
<select name="cat[color]" value="<%= @cat.color%>">
  <option value="Infrared">Infrared</option>
  <option value="Red">Red</option>
  <option value="Orange">Orange</option>
  <option value="Yellow">Yellow</option>
  <option value="Green">Green</option>
  <option value="Blue">Blue</option>
  <option value="Indigo">Indigo</option>
  <option value="Violet">Violet</option>
  <option value="Ultraviolet">Ultraviolet</option>
</select>
</label>

<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

<input type="submit" value="submit">

</form>

app/views/cats/index.html.erb
<h1>All the Cats you may rent</h1>
<ul>
  <% @all_cats.each do |cat| %>
  <li>
    Name: <%= cat.name %>
  </li>
  <ul>
    <li>Age: <%= cat.age %></li>
    <li>Birth Date: <%= cat.birth_date%></li>
    <li>Color: <%= cat.color%></li>
    <li>Sex: <%= cat.sex%></li>
  </ul>
  <% end %>
</ul>

app/views/cats/new.html.erb
<%= form_for @cat, url: cats_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :age %>
<%= f.text_field :age %>

<%= f.label :sex %>
<%= f.text_field :sex %>

<input type="hidden" name="cat[user_id]" value="<%=
  User.find_by_token(session[:token]).id
%>">

<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

<label for="cat_birth_date">Birth Date</label>
<input type="date" name="cat[birth_date]" id="cat_birth_date">

<%= f.label :color %>
<%= f.select :color, options_for_select([ ["Infrared", "Infrared"], ["Red", "Red"], ["Orange", "Orange"], ["Yellow", "Yellow"], ["Green", "Green"], ["Blue", "Blue"], ["Indigo", "Indigo"], ["Violet", "Violet"], ["Ultraviolet", "Ultraviolet"]  ], :color)   %>

<%= f.submit "Continue" %>
<% end %>

app/views/cats/show.html.erb
<h1>About <%= @cat.name %></h1>

<ul>
  <li>Age: <%= @cat.age %></li>
  <li>Birth Date: <%= @cat.birth_date%></li>
  <li>Color: <%= @cat.color%></li>
  <li>Sex: <%= @cat.sex%></li>
</ul>

<h2>Orders for <%= @cat.name %></h2>
<ul>
  <% @cat.cat_rental_requests.each do |request| %>
  <li>One <%= request.status %> request for <%= request.begin_date %> through <%= request.end_date %> </li>

    <% if request.status == "undecided" &&
         @cat.user_id == User.find_by_token(session[:token]).id %>
    <li>

      <form action="<%=cat_rental_request_path(request.id)%>" method="post">


        <label>Approve
        <input type="radio" name="cat_rental_request[status]" value="approve"></label>

        <label>Deny
        <input type="radio" name="cat_rental_request[status]" value="deny"></label>

        <input type="hidden"
                 name="authenticity_token"
                 value="<%= form_authenticity_token %>">

        <input type="hidden" name="_method" value="put">
        <input type="submit" value="submit">
      </form>
    </li>
    <% end %>
  <% end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatRental</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="<%= users_path %>" method="post">
  <label>Username
    <input type="text" name="user[username]" value="user[username]">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="user[password]">
  </label>
  <input type="submit" value="submit">
</form>